spring.application.name=bookshelf
server.port=${PORT:9090}

##PRODUCTION SETTINGS
#spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=${MYSQLUSER}
#spring.datasource.password=${MYSQLPASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#app.useSecureCookie = true
#frontend.url=https://bookshelf-by-ishika.vercel.app

##LOCAL SETTINGS
spring.datasource.url=jdbc:mysql://localhost:3306/bookshelf
spring.datasource.username=${DB_User}
spring.datasource.password=${DB_Pass}
#(create, update, create-drop, validate)
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
app.useSecureCookie = false
frontend.url=http://localhost:5174
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

##REDIS SETTINGS
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

##STMP SETTINGS
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

##RABBITMQ SETTINGS
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.multiplier=2

##GENERAL
api.prefix=/api/v1
# 1 day
auth.token.accessExpirationInMils=86400000
# 2 day
auth.token.refreshExpirationInMils=172800000
spring.ai.transformers.embedding.enabled=true



