spring.application.name=bookshelf
server.port=${PORT:9090}

##PRODUCTION SETTINGS
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
app.useSecureCookie = true
frontend.url=https://bookshelf-by-ishika.vercel.app
##LOCAL SETTINGS
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

api.prefix=/api/v1

# 15 minutes
auth.token.accessExpirationInMils=900000
# 1 day
auth.token.refreshExpirationInMils=86400000

spring.ai.transformers.embedding.enabled=true



